In [1]:
import numpy as np

In [3]:
A=np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [4]:
autovalores, autovectores=np.linalg.eig(A)

In [6]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [9]:
A_cal=autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
print(A_cal)

[[3. 2.]
 [4. 1.]]


In [10]:
A=np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [11]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [12]:
autovalores, autovectores=np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [13]:
A_calc=autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
